version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - aws s3 cp . s3://ajhollowaydev.com/ --recursive --acl public-read-write

artifacts:
  files:
    - "**/*"