version: 0.2

phases:
  build:
    commands:
build:
    commands:
      - echo Build started on `date`
      - aws s3 cp dist s3://holloway-portfoliio/ --recursive
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    -  "**/*"